# Generated by Django 4.1 on 2022-10-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='hasActor',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='noOfPlayers',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='noOfRiddles',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='scenario',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='projects.userprofileinfo'),
        ),
    ]
